#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 24 19:35:14 2020

@author: zhengs
"""


datas = {'A001':['小熊軟糖', 20],'A002':['冰棒',25],
          'A004':['王子麵',10],'A006':['汽水',30]}
num=input('請輸入貨號：')
if num not in datas:
    print('貨號：{} 不存在'.format(num))
    new = input('1:新增商品；2:離開系統')
    if new=='1':
        name=input('請輸入品項：')
        money=int(input('請輸入售價：'))
        datas[num]=[name,money]
        d = datas.get(num)
        print('貨號：{} 品項：{} 價格：{}元'.format(num,d[0],d[1]))

    elif new=='2':
        pass
    else:
        print('輸入錯誤，請重新輸入!')