#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 29 18:46:46 2020

@author: zhengs
"""


a=[]
b=input("班上共有多少人?")
for i in range(int(b)):
    score=int(input("score?"))
    a.append(score)
    
t=0
for i in a:
    t=t+i
        
print("average=",t//int(b))
